/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SiteRouteImport } from './routes/_site'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CuentaRouteImport } from './routes/cuenta'
import { Route as SiteIndexRouteImport } from './routes/_site/index'
import { Route as SiteAdoptaRouteImport } from './routes/_site/adopta'
import { Route as SiteContactoRouteImport } from './routes/_site/contacto'
import { Route as SiteDenunciasRouteImport } from './routes/_site/denuncias'
import { Route as SiteDonacionesRouteImport } from './routes/_site/donaciones'
import { Route as SiteEventosRouteImport } from './routes/_site/eventos'
import { Route as SiteFavoritosRouteImport } from './routes/_site/favoritos'
import { Route as SiteNosotrosRouteImport } from './routes/_site/nosotros'
import { Route as SitePoliticasRouteImport } from './routes/_site/politicas'
import { Route as SiteTerminosRouteImport } from './routes/_site/terminos'
import { Route as SiteTiendaRouteImport } from './routes/_site/tienda'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminDenunciasRouteImport } from './routes/admin/denuncias'
import { Route as AdminDonacionesRouteImport } from './routes/admin/donaciones'
import { Route as AdminEventosRouteImport } from './routes/admin/eventos'
import { Route as AdminMascotasRouteImport } from './routes/admin/mascotas'
import { Route as AdminPedidosRouteImport } from './routes/admin/pedidos'
import { Route as AdminProductosRouteImport } from './routes/admin/productos'
import { Route as AdminReportesRouteImport } from './routes/admin/reportes'
import { Route as AdminSolicitudesRouteImport } from './routes/admin/solicitudes'
import { Route as AdminUsuariosRouteImport } from './routes/admin/usuarios'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthRegistroRouteImport } from './routes/auth/registro'
import { Route as CuentaIndexRouteImport } from './routes/cuenta/index'
import { Route as CuentaDonacionesRouteImport } from './routes/cuenta/donaciones'
import { Route as CuentaMensajesRouteImport } from './routes/cuenta/mensajes'
import { Route as CuentaNotificacionesRouteImport } from './routes/cuenta/notificaciones'
import { Route as CuentaPedidosRouteImport } from './routes/cuenta/pedidos'
import { Route as CuentaPerfilRouteImport } from './routes/cuenta/perfil'
import { Route as CuentaSolicitudesRouteImport } from './routes/cuenta/solicitudes'
import { Route as SiteMascotasIndexRouteImport } from './routes/_site/mascotas/index'
import { Route as SiteMascotasIdRouteImport } from './routes/_site/mascotas/$id'

const SiteRoute = SiteRouteImport.update({
  id: '/_site',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CuentaRoute = CuentaRouteImport.update({
  id: '/cuenta',
  path: '/cuenta',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteIndexRoute = SiteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteAdoptaRoute = SiteAdoptaRouteImport.update({
  id: '/adopta',
  path: '/adopta',
  getParentRoute: () => SiteRoute,
} as any)
const SiteContactoRoute = SiteContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => SiteRoute,
} as any)
const SiteDenunciasRoute = SiteDenunciasRouteImport.update({
  id: '/denuncias',
  path: '/denuncias',
  getParentRoute: () => SiteRoute,
} as any)
const SiteDonacionesRoute = SiteDonacionesRouteImport.update({
  id: '/donaciones',
  path: '/donaciones',
  getParentRoute: () => SiteRoute,
} as any)
const SiteEventosRoute = SiteEventosRouteImport.update({
  id: '/eventos',
  path: '/eventos',
  getParentRoute: () => SiteRoute,
} as any)
const SiteFavoritosRoute = SiteFavoritosRouteImport.update({
  id: '/favoritos',
  path: '/favoritos',
  getParentRoute: () => SiteRoute,
} as any)
const SiteNosotrosRoute = SiteNosotrosRouteImport.update({
  id: '/nosotros',
  path: '/nosotros',
  getParentRoute: () => SiteRoute,
} as any)
const SitePoliticasRoute = SitePoliticasRouteImport.update({
  id: '/politicas',
  path: '/politicas',
  getParentRoute: () => SiteRoute,
} as any)
const SiteTerminosRoute = SiteTerminosRouteImport.update({
  id: '/terminos',
  path: '/terminos',
  getParentRoute: () => SiteRoute,
} as any)
const SiteTiendaRoute = SiteTiendaRouteImport.update({
  id: '/tienda',
  path: '/tienda',
  getParentRoute: () => SiteRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDenunciasRoute = AdminDenunciasRouteImport.update({
  id: '/denuncias',
  path: '/denuncias',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDonacionesRoute = AdminDonacionesRouteImport.update({
  id: '/donaciones',
  path: '/donaciones',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventosRoute = AdminEventosRouteImport.update({
  id: '/eventos',
  path: '/eventos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMascotasRoute = AdminMascotasRouteImport.update({
  id: '/mascotas',
  path: '/mascotas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPedidosRoute = AdminPedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductosRoute = AdminProductosRouteImport.update({
  id: '/productos',
  path: '/productos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportesRoute = AdminReportesRouteImport.update({
  id: '/reportes',
  path: '/reportes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSolicitudesRoute = AdminSolicitudesRouteImport.update({
  id: '/solicitudes',
  path: '/solicitudes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsuariosRoute = AdminUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AdminRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegistroRoute = AuthRegistroRouteImport.update({
  id: '/auth/registro',
  path: '/auth/registro',
  getParentRoute: () => rootRouteImport,
} as any)
const CuentaIndexRoute = CuentaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CuentaRoute,
} as any)
const CuentaDonacionesRoute = CuentaDonacionesRouteImport.update({
  id: '/donaciones',
  path: '/donaciones',
  getParentRoute: () => CuentaRoute,
} as any)
const CuentaMensajesRoute = CuentaMensajesRouteImport.update({
  id: '/mensajes',
  path: '/mensajes',
  getParentRoute: () => CuentaRoute,
} as any)
const CuentaNotificacionesRoute = CuentaNotificacionesRouteImport.update({
  id: '/notificaciones',
  path: '/notificaciones',
  getParentRoute: () => CuentaRoute,
} as any)
const CuentaPedidosRoute = CuentaPedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => CuentaRoute,
} as any)
const CuentaPerfilRoute = CuentaPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => CuentaRoute,
} as any)
const CuentaSolicitudesRoute = CuentaSolicitudesRouteImport.update({
  id: '/solicitudes',
  path: '/solicitudes',
  getParentRoute: () => CuentaRoute,
} as any)
const SiteMascotasIndexRoute = SiteMascotasIndexRouteImport.update({
  id: '/mascotas/',
  path: '/mascotas/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteMascotasIdRoute = SiteMascotasIdRouteImport.update({
  id: '/mascotas/$id',
  path: '/mascotas/$id',
  getParentRoute: () => SiteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof SiteIndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/cuenta': typeof CuentaRouteWithChildren
  '/adopta': typeof SiteAdoptaRoute
  '/contacto': typeof SiteContactoRoute
  '/denuncias': typeof SiteDenunciasRoute
  '/donaciones': typeof SiteDonacionesRoute
  '/eventos': typeof SiteEventosRoute
  '/favoritos': typeof SiteFavoritosRoute
  '/nosotros': typeof SiteNosotrosRoute
  '/politicas': typeof SitePoliticasRoute
  '/terminos': typeof SiteTerminosRoute
  '/tienda': typeof SiteTiendaRoute
  '/admin/denuncias': typeof AdminDenunciasRoute
  '/admin/donaciones': typeof AdminDonacionesRoute
  '/admin/eventos': typeof AdminEventosRoute
  '/admin/mascotas': typeof AdminMascotasRoute
  '/admin/pedidos': typeof AdminPedidosRoute
  '/admin/productos': typeof AdminProductosRoute
  '/admin/reportes': typeof AdminReportesRoute
  '/admin/solicitudes': typeof AdminSolicitudesRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/registro': typeof AuthRegistroRoute
  '/cuenta/donaciones': typeof CuentaDonacionesRoute
  '/cuenta/mensajes': typeof CuentaMensajesRoute
  '/cuenta/notificaciones': typeof CuentaNotificacionesRoute
  '/cuenta/pedidos': typeof CuentaPedidosRoute
  '/cuenta/perfil': typeof CuentaPerfilRoute
  '/cuenta/solicitudes': typeof CuentaSolicitudesRoute
  '/admin/': typeof AdminIndexRoute
  '/cuenta/': typeof CuentaIndexRoute
  '/mascotas/$id': typeof SiteMascotasIdRoute
  '/mascotas/': typeof SiteMascotasIndexRoute
}
export interface FileRoutesByTo {
  '/adopta': typeof SiteAdoptaRoute
  '/contacto': typeof SiteContactoRoute
  '/denuncias': typeof SiteDenunciasRoute
  '/donaciones': typeof SiteDonacionesRoute
  '/eventos': typeof SiteEventosRoute
  '/favoritos': typeof SiteFavoritosRoute
  '/nosotros': typeof SiteNosotrosRoute
  '/politicas': typeof SitePoliticasRoute
  '/terminos': typeof SiteTerminosRoute
  '/tienda': typeof SiteTiendaRoute
  '/admin/denuncias': typeof AdminDenunciasRoute
  '/admin/donaciones': typeof AdminDonacionesRoute
  '/admin/eventos': typeof AdminEventosRoute
  '/admin/mascotas': typeof AdminMascotasRoute
  '/admin/pedidos': typeof AdminPedidosRoute
  '/admin/productos': typeof AdminProductosRoute
  '/admin/reportes': typeof AdminReportesRoute
  '/admin/solicitudes': typeof AdminSolicitudesRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/registro': typeof AuthRegistroRoute
  '/cuenta/donaciones': typeof CuentaDonacionesRoute
  '/cuenta/mensajes': typeof CuentaMensajesRoute
  '/cuenta/notificaciones': typeof CuentaNotificacionesRoute
  '/cuenta/pedidos': typeof CuentaPedidosRoute
  '/cuenta/perfil': typeof CuentaPerfilRoute
  '/cuenta/solicitudes': typeof CuentaSolicitudesRoute
  '/': typeof SiteIndexRoute
  '/admin': typeof AdminIndexRoute
  '/cuenta': typeof CuentaIndexRoute
  '/mascotas/$id': typeof SiteMascotasIdRoute
  '/mascotas': typeof SiteMascotasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_site': typeof SiteRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/cuenta': typeof CuentaRouteWithChildren
  '/_site/adopta': typeof SiteAdoptaRoute
  '/_site/contacto': typeof SiteContactoRoute
  '/_site/denuncias': typeof SiteDenunciasRoute
  '/_site/donaciones': typeof SiteDonacionesRoute
  '/_site/eventos': typeof SiteEventosRoute
  '/_site/favoritos': typeof SiteFavoritosRoute
  '/_site/nosotros': typeof SiteNosotrosRoute
  '/_site/politicas': typeof SitePoliticasRoute
  '/_site/terminos': typeof SiteTerminosRoute
  '/_site/tienda': typeof SiteTiendaRoute
  '/admin/denuncias': typeof AdminDenunciasRoute
  '/admin/donaciones': typeof AdminDonacionesRoute
  '/admin/eventos': typeof AdminEventosRoute
  '/admin/mascotas': typeof AdminMascotasRoute
  '/admin/pedidos': typeof AdminPedidosRoute
  '/admin/productos': typeof AdminProductosRoute
  '/admin/reportes': typeof AdminReportesRoute
  '/admin/solicitudes': typeof AdminSolicitudesRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/registro': typeof AuthRegistroRoute
  '/cuenta/donaciones': typeof CuentaDonacionesRoute
  '/cuenta/mensajes': typeof CuentaMensajesRoute
  '/cuenta/notificaciones': typeof CuentaNotificacionesRoute
  '/cuenta/pedidos': typeof CuentaPedidosRoute
  '/cuenta/perfil': typeof CuentaPerfilRoute
  '/cuenta/solicitudes': typeof CuentaSolicitudesRoute
  '/_site/': typeof SiteIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/cuenta/': typeof CuentaIndexRoute
  '/_site/mascotas/$id': typeof SiteMascotasIdRoute
  '/_site/mascotas/': typeof SiteMascotasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/cuenta'
    | '/adopta'
    | '/contacto'
    | '/denuncias'
    | '/donaciones'
    | '/eventos'
    | '/favoritos'
    | '/nosotros'
    | '/politicas'
    | '/terminos'
    | '/tienda'
    | '/admin/denuncias'
    | '/admin/donaciones'
    | '/admin/eventos'
    | '/admin/mascotas'
    | '/admin/pedidos'
    | '/admin/productos'
    | '/admin/reportes'
    | '/admin/solicitudes'
    | '/admin/usuarios'
    | '/auth/login'
    | '/auth/registro'
    | '/cuenta/donaciones'
    | '/cuenta/mensajes'
    | '/cuenta/notificaciones'
    | '/cuenta/pedidos'
    | '/cuenta/perfil'
    | '/cuenta/solicitudes'
    | '/admin/'
    | '/cuenta/'
    | '/mascotas/$id'
    | '/mascotas/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/adopta'
    | '/contacto'
    | '/denuncias'
    | '/donaciones'
    | '/eventos'
    | '/favoritos'
    | '/nosotros'
    | '/politicas'
    | '/terminos'
    | '/tienda'
    | '/admin/denuncias'
    | '/admin/donaciones'
    | '/admin/eventos'
    | '/admin/mascotas'
    | '/admin/pedidos'
    | '/admin/productos'
    | '/admin/reportes'
    | '/admin/solicitudes'
    | '/admin/usuarios'
    | '/auth/login'
    | '/auth/registro'
    | '/cuenta/donaciones'
    | '/cuenta/mensajes'
    | '/cuenta/notificaciones'
    | '/cuenta/pedidos'
    | '/cuenta/perfil'
    | '/cuenta/solicitudes'
    | '/'
    | '/admin'
    | '/cuenta'
    | '/mascotas/$id'
    | '/mascotas'
  id:
    | '__root__'
    | '/_site'
    | '/admin'
    | '/cuenta'
    | '/_site/adopta'
    | '/_site/contacto'
    | '/_site/denuncias'
    | '/_site/donaciones'
    | '/_site/eventos'
    | '/_site/favoritos'
    | '/_site/nosotros'
    | '/_site/politicas'
    | '/_site/terminos'
    | '/_site/tienda'
    | '/admin/denuncias'
    | '/admin/donaciones'
    | '/admin/eventos'
    | '/admin/mascotas'
    | '/admin/pedidos'
    | '/admin/productos'
    | '/admin/reportes'
    | '/admin/solicitudes'
    | '/admin/usuarios'
    | '/auth/login'
    | '/auth/registro'
    | '/cuenta/donaciones'
    | '/cuenta/mensajes'
    | '/cuenta/notificaciones'
    | '/cuenta/pedidos'
    | '/cuenta/perfil'
    | '/cuenta/solicitudes'
    | '/_site/'
    | '/admin/'
    | '/cuenta/'
    | '/_site/mascotas/$id'
    | '/_site/mascotas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SiteRoute: typeof SiteRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  CuentaRoute: typeof CuentaRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegistroRoute: typeof AuthRegistroRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_site': {
      id: '/_site'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cuenta': {
      id: '/cuenta'
      path: '/cuenta'
      fullPath: '/cuenta'
      preLoaderRoute: typeof CuentaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site/': {
      id: '/_site/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SiteIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/adopta': {
      id: '/_site/adopta'
      path: '/adopta'
      fullPath: '/adopta'
      preLoaderRoute: typeof SiteAdoptaRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/contacto': {
      id: '/_site/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof SiteContactoRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/denuncias': {
      id: '/_site/denuncias'
      path: '/denuncias'
      fullPath: '/denuncias'
      preLoaderRoute: typeof SiteDenunciasRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/donaciones': {
      id: '/_site/donaciones'
      path: '/donaciones'
      fullPath: '/donaciones'
      preLoaderRoute: typeof SiteDonacionesRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/eventos': {
      id: '/_site/eventos'
      path: '/eventos'
      fullPath: '/eventos'
      preLoaderRoute: typeof SiteEventosRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/favoritos': {
      id: '/_site/favoritos'
      path: '/favoritos'
      fullPath: '/favoritos'
      preLoaderRoute: typeof SiteFavoritosRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/nosotros': {
      id: '/_site/nosotros'
      path: '/nosotros'
      fullPath: '/nosotros'
      preLoaderRoute: typeof SiteNosotrosRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/politicas': {
      id: '/_site/politicas'
      path: '/politicas'
      fullPath: '/politicas'
      preLoaderRoute: typeof SitePoliticasRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/terminos': {
      id: '/_site/terminos'
      path: '/terminos'
      fullPath: '/terminos'
      preLoaderRoute: typeof SiteTerminosRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/tienda': {
      id: '/_site/tienda'
      path: '/tienda'
      fullPath: '/tienda'
      preLoaderRoute: typeof SiteTiendaRouteImport
      parentRoute: typeof SiteRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/denuncias': {
      id: '/admin/denuncias'
      path: '/denuncias'
      fullPath: '/admin/denuncias'
      preLoaderRoute: typeof AdminDenunciasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/donaciones': {
      id: '/admin/donaciones'
      path: '/donaciones'
      fullPath: '/admin/donaciones'
      preLoaderRoute: typeof AdminDonacionesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/eventos': {
      id: '/admin/eventos'
      path: '/eventos'
      fullPath: '/admin/eventos'
      preLoaderRoute: typeof AdminEventosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/mascotas': {
      id: '/admin/mascotas'
      path: '/mascotas'
      fullPath: '/admin/mascotas'
      preLoaderRoute: typeof AdminMascotasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pedidos': {
      id: '/admin/pedidos'
      path: '/pedidos'
      fullPath: '/admin/pedidos'
      preLoaderRoute: typeof AdminPedidosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/productos': {
      id: '/admin/productos'
      path: '/productos'
      fullPath: '/admin/productos'
      preLoaderRoute: typeof AdminProductosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reportes': {
      id: '/admin/reportes'
      path: '/reportes'
      fullPath: '/admin/reportes'
      preLoaderRoute: typeof AdminReportesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/solicitudes': {
      id: '/admin/solicitudes'
      path: '/solicitudes'
      fullPath: '/admin/solicitudes'
      preLoaderRoute: typeof AdminSolicitudesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/usuarios': {
      id: '/admin/usuarios'
      path: '/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AdminUsuariosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/registro': {
      id: '/auth/registro'
      path: '/auth/registro'
      fullPath: '/auth/registro'
      preLoaderRoute: typeof AuthRegistroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cuenta/': {
      id: '/cuenta/'
      path: '/'
      fullPath: '/cuenta/'
      preLoaderRoute: typeof CuentaIndexRouteImport
      parentRoute: typeof CuentaRoute
    }
    '/cuenta/donaciones': {
      id: '/cuenta/donaciones'
      path: '/donaciones'
      fullPath: '/cuenta/donaciones'
      preLoaderRoute: typeof CuentaDonacionesRouteImport
      parentRoute: typeof CuentaRoute
    }
    '/cuenta/mensajes': {
      id: '/cuenta/mensajes'
      path: '/mensajes'
      fullPath: '/cuenta/mensajes'
      preLoaderRoute: typeof CuentaMensajesRouteImport
      parentRoute: typeof CuentaRoute
    }
    '/cuenta/notificaciones': {
      id: '/cuenta/notificaciones'
      path: '/notificaciones'
      fullPath: '/cuenta/notificaciones'
      preLoaderRoute: typeof CuentaNotificacionesRouteImport
      parentRoute: typeof CuentaRoute
    }
    '/cuenta/pedidos': {
      id: '/cuenta/pedidos'
      path: '/pedidos'
      fullPath: '/cuenta/pedidos'
      preLoaderRoute: typeof CuentaPedidosRouteImport
      parentRoute: typeof CuentaRoute
    }
    '/cuenta/perfil': {
      id: '/cuenta/perfil'
      path: '/perfil'
      fullPath: '/cuenta/perfil'
      preLoaderRoute: typeof CuentaPerfilRouteImport
      parentRoute: typeof CuentaRoute
    }
    '/cuenta/solicitudes': {
      id: '/cuenta/solicitudes'
      path: '/solicitudes'
      fullPath: '/cuenta/solicitudes'
      preLoaderRoute: typeof CuentaSolicitudesRouteImport
      parentRoute: typeof CuentaRoute
    }
    '/_site/mascotas/': {
      id: '/_site/mascotas/'
      path: '/mascotas'
      fullPath: '/mascotas/'
      preLoaderRoute: typeof SiteMascotasIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/mascotas/$id': {
      id: '/_site/mascotas/$id'
      path: '/mascotas/$id'
      fullPath: '/mascotas/$id'
      preLoaderRoute: typeof SiteMascotasIdRouteImport
      parentRoute: typeof SiteRoute
    }
  }
}

interface SiteRouteChildren {
  SiteAdoptaRoute: typeof SiteAdoptaRoute
  SiteContactoRoute: typeof SiteContactoRoute
  SiteDenunciasRoute: typeof SiteDenunciasRoute
  SiteDonacionesRoute: typeof SiteDonacionesRoute
  SiteEventosRoute: typeof SiteEventosRoute
  SiteFavoritosRoute: typeof SiteFavoritosRoute
  SiteNosotrosRoute: typeof SiteNosotrosRoute
  SitePoliticasRoute: typeof SitePoliticasRoute
  SiteTerminosRoute: typeof SiteTerminosRoute
  SiteTiendaRoute: typeof SiteTiendaRoute
  SiteIndexRoute: typeof SiteIndexRoute
  SiteMascotasIdRoute: typeof SiteMascotasIdRoute
  SiteMascotasIndexRoute: typeof SiteMascotasIndexRoute
}

const SiteRouteChildren: SiteRouteChildren = {
  SiteAdoptaRoute: SiteAdoptaRoute,
  SiteContactoRoute: SiteContactoRoute,
  SiteDenunciasRoute: SiteDenunciasRoute,
  SiteDonacionesRoute: SiteDonacionesRoute,
  SiteEventosRoute: SiteEventosRoute,
  SiteFavoritosRoute: SiteFavoritosRoute,
  SiteNosotrosRoute: SiteNosotrosRoute,
  SitePoliticasRoute: SitePoliticasRoute,
  SiteTerminosRoute: SiteTerminosRoute,
  SiteTiendaRoute: SiteTiendaRoute,
  SiteIndexRoute: SiteIndexRoute,
  SiteMascotasIdRoute: SiteMascotasIdRoute,
  SiteMascotasIndexRoute: SiteMascotasIndexRoute,
}

const SiteRouteWithChildren = SiteRoute._addFileChildren(SiteRouteChildren)

interface AdminRouteChildren {
  AdminDenunciasRoute: typeof AdminDenunciasRoute
  AdminDonacionesRoute: typeof AdminDonacionesRoute
  AdminEventosRoute: typeof AdminEventosRoute
  AdminMascotasRoute: typeof AdminMascotasRoute
  AdminPedidosRoute: typeof AdminPedidosRoute
  AdminProductosRoute: typeof AdminProductosRoute
  AdminReportesRoute: typeof AdminReportesRoute
  AdminSolicitudesRoute: typeof AdminSolicitudesRoute
  AdminUsuariosRoute: typeof AdminUsuariosRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminDenunciasRoute: AdminDenunciasRoute,
  AdminDonacionesRoute: AdminDonacionesRoute,
  AdminEventosRoute: AdminEventosRoute,
  AdminMascotasRoute: AdminMascotasRoute,
  AdminPedidosRoute: AdminPedidosRoute,
  AdminProductosRoute: AdminProductosRoute,
  AdminReportesRoute: AdminReportesRoute,
  AdminSolicitudesRoute: AdminSolicitudesRoute,
  AdminUsuariosRoute: AdminUsuariosRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface CuentaRouteChildren {
  CuentaDonacionesRoute: typeof CuentaDonacionesRoute
  CuentaMensajesRoute: typeof CuentaMensajesRoute
  CuentaNotificacionesRoute: typeof CuentaNotificacionesRoute
  CuentaPedidosRoute: typeof CuentaPedidosRoute
  CuentaPerfilRoute: typeof CuentaPerfilRoute
  CuentaSolicitudesRoute: typeof CuentaSolicitudesRoute
  CuentaIndexRoute: typeof CuentaIndexRoute
}

const CuentaRouteChildren: CuentaRouteChildren = {
  CuentaDonacionesRoute: CuentaDonacionesRoute,
  CuentaMensajesRoute: CuentaMensajesRoute,
  CuentaNotificacionesRoute: CuentaNotificacionesRoute,
  CuentaPedidosRoute: CuentaPedidosRoute,
  CuentaPerfilRoute: CuentaPerfilRoute,
  CuentaSolicitudesRoute: CuentaSolicitudesRoute,
  CuentaIndexRoute: CuentaIndexRoute,
}

const CuentaRouteWithChildren =
  CuentaRoute._addFileChildren(CuentaRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  SiteRoute: SiteRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  CuentaRoute: CuentaRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegistroRoute: AuthRegistroRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
